### ISSUE TITLE
Sono alcuni giorni che ho questo errore nel run del programma

### ISSUE THREAD

**Issue by giobru56** [jacopo-j/tnt-downloader#17]
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Caricamento dati in corso...
Traceback (most recent call last):
  File "./tnt-downloader.py", line 337, in <module>
    main()
  File "./tnt-downloader.py", line 333, in main
    do_search(args.query, chunks_size)
  File "./tnt-downloader.py", line 121, in do_search
    tot_pages = int(search_tree.xpath(tot_pag_addr)[0])
IndexError: list index out of range

**Comment by jacopo-j** [comment]
La pagina delle releases di TNTVillage ([http://tntvillage.scambioetico.org/?releaselist](http://tntvillage.scambioetico.org/?releaselist)) è down, lo script dipende da quella pagina e quindi non funzionerà fino a quanto la pagina non sarà nuovamente disponibile.
