### ISSUE TITLE
Mostrare il numero di seed e di leech dei torrent

### ISSUE THREAD

**Issue by jacopo-j** [jacopo-j/tnt-downloader#5]
Aggiungo questo enhancement fin dall'inizio, non ho integrato la funzione nella prima release perché non sono sicuro di come sarebbe meglio inserire questi dati in modo chiaro da un punto di vista estetico. Magari dopo il numero dell'elenco? Si rischia però di restringere troppo lo spazio che viene lasciato a disposizione per il titolo e la descrizione. Si accettano suggerimenti.

**Comment by GiovanniGrieco** [comment]
Si potrebbe simulare il layout del sito e in caso troncare le stringhe lunghe?

Per la generazione delle tabelle potresti ricorrere ad una utility esterna per non perder tempo, tipo [Robpol86/terminaltables](https://github.com/Robpol86/terminaltables)

**Comment by msx80** [comment]
concordo che i due numeri sono molto importanti, in caso piuttosto tronca i titoli o metti una terza riga
